### ISSUE TITLE
Lack of 1.19.3

### ISSUE THREAD

**Issue by TextualMold9830** [DavideBlade/Clash-of-Minecrafters#14]
### Tasks

- [X] I have read the [wiki](https://github.com/DavideBlade/Clash-of-Minecrafters/wiki).
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/DavideBlade/Clash-of-Minecrafters/issues?q=is%3Aissue).
- [X] I have tested the [latest version](https://www.spigotmc.org/resources/31180/history) of Clash of Minecrafters and the bug is still there.

### What happened?

java.lang.RuntimeException: Unknown server version: org.bukkit.craftbukkit.v1_19_R2
[16:11:33] [Server thread/WARN]: 	at com.gmail.davideblade99.clashofminecrafters.CoM.setupVillageWorld(CoM.java:342)
[16:11:33] [Server thread/WARN]: 	at com.gmail.davideblade99.clashofminecrafters.CoM.onEnable(CoM.java:174)
[16:11:33] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[16:11:33] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
[16:11:33] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[16:11:33] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:539)
[16:11:33] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:453)
[16:11:33] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:587)
[16:11:33] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:412)
[16:11:33] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250)
[16:11:33] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:973)
[16:11:33] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:301)
[16:11:33] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[16:11:33] [Server thread/INFO]: [CoM] Clash of minecrafters has been disabled. (Version: 3.1.2 alpha)

### Reproduction of the problem

Starting a 1.19.3 results in a crash.

### Server version

CraftBukkit version 3661-Spigot-19641c7-8434e36

### Plugin version

v3.1.2 alpha

**Comment by DavideBlade** [comment]
Thank you for the report! There is currently a change in the plugin in development that makes it complicated to post a quick update for the addition of 1.19.3 but this will be done more or less soon (depending on how long the update takes that I am already working on).

If you can use it, you can still start working on it using 1.19.2 (latest supported version).

**Comment by DavideBlade** [comment]
Feature added in version 3.1.5 ([#15bc9e2](https://github.com/DavideBlade/Clash-of-Minecrafters/commit/15bc9e27aee3444fe652140d42b8d3f35e56673c)). Thank you for waiting!
