### ISSUE TITLE
Cannot Start

### ISSUE THREAD

**Issue by MoleAfec** [DavideBlade/Clash-of-Minecrafters#19]
### Tasks

- [X] I have read the [wiki](https://github.com/DavideBlade/Clash-of-Minecrafters/wiki).
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/DavideBlade/Clash-of-Minecrafters/issues?q=is%3Aissue).
- [X] I have tested the [latest version](https://www.spigotmc.org/resources/31180/history) of Clash of Minecrafters and the bug is still there.

### What happened?

Whenever I try to start the server I get this error

21:20:24 INFO]: [CoM] Enabling CoM v3.2 alpha
[21:20:25 WARN]: java.lang.RuntimeException: Unknown server version: org.bukkit.craftbukkit.v1_20_R3
[21:20:25 WARN]: 	at CoM.jar//com.gmail.davideblade99.clashofminecrafters.CoM.setupVillageWorld(CoM.java:313)
[21:20:25 WARN]: 	at CoM.jar//com.gmail.davideblade99.clashofminecrafters.CoM.onEnable(CoM.java:136)
[21:20:25 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
[21:20:25 WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:190)
[21:20:25 WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[21:20:25 WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[21:20:25 WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:637)
[21:20:25 WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:548)
[21:20:25 WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:673)
[21:20:25 WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:433)
[21:20:25 WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
[21:20:25 WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1132)
[21:20:25 WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321)
[21:20:25 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[21:20:25 INFO]: [CoM] Clash of minecrafters has been disabled. (Version: 3.2 alpha)

then the server starts and the plugin is disabled, how could I possibly fix this? Thank you.

### Reproduction of the problem

1. I start the server
2. Console gives me the error
3. Server starts with the plugin disabled

### Server version

Paper version-git-Paper-336

### Plugin version

3.2.1 alpha

**Comment by DavideBlade** [comment]
As you can see from the output, the plugin version is 3.2 instead of the latest (3.2.1). In any case the problem you reported occurs anyway, I mistakenly uploaded the wrong .jar file.
Please download version 3.2.1 on Spigot now and confirm that it works correctly.

(Don't forget to install [Citizens](https://www.spigotmc.org/resources/citizens.13811/), new mandatory dependency)

**Comment by MoleAfec** [comment]
Thank you it seems to work properly now! I appreciate the quick feedback.
